---
title: "Manhattan Prep"
author: "Brett Burk"
output: 
  pdf_document: 
    number_sections: false
    fig_height: 11
    fig_width: 8.5
geometry: margin=0.5in
header-includes:
  - \usepackage{graphicx}
  - \usepackage{hyperref}
  - \usepackage{xcolor}
  - \usepackage{setspace}
---

why xls at all?

```{r load-in}


folder <- "E:\\Projects\\manhattanPrep\\"
api.key <- read.table(paste0(folder, "convertAPIKey"))
wf <- read.csv(paste0(folder, "GMATraw.csv"), stringsAsFactors = FALSE)
head(wf)
ques <- read.csv(paste0(folder, "GMATrawQues.csv"), stringsAsFactors = FALSE)
names(wf) <- ques[,2]
nrow(wf)
cs <- read.csv(paste0(folder, "CodeSheet.csv"), stringsAsFactors = FALSE)
```

```{r light exploration}


# Checking for repeat students
sum(table(wf[,1]) >= 2)

library(knitr)
# Skip 1 for student ID
for(i in 2:ncol(wf)){
  cat('--------------------------------------------------------  \n')
  cat(paste0(i, ". ", ques[i,2]))
  print(table(wf[,i], exclude = NULL))
}

library(pdftables)
convert_pdf(paste0(folder, "CodeSheet.pdf"), paste0(folder, "codesheetcsv.csv"), api_key = "")
